### PR TITLE
FIX pass NOGOSU=True for compatibility wirh odoo-bedrock

### PR DESCRIPTION
**Pull request by sebastienbeau**
Note: compatible with old project

### CODE REVIEW

**Comment by PierrickBrun** [comment]
tested with both odoo-bedrock and camptocamp's image

**Review by PierrickBrun — APPROVED** [review]

**Review by florian-dacosta — APPROVED** [review]

**Comment by hparfr** [comment]
Why not in docker-compose ?

**Comment by sebastienbeau** [comment]
Because it should be passed only for docky run or open. Not for docky up

**Comment by sebastienbeau** [comment]
Idealy we can not pass the arg "gosu odoo bash" by default and only pass "NOGUSO=TRUE" when passing args --root. But this will break compatibility with C2C image. So when we will not use anymore C2C image we can clean it.

**Pull request merged**
